import {
  Transaction,
  ShoppingList,
  ShoppingItem,
  Bill,
  BudgetLimit,
} from './types';

export const INITIAL_CATEGORIES = [
  { name: 'Jedzenie i artykuły spożywcze', color: '#10b981', icon: 'Utensils' },
  { name: 'Remont i dom', color: '#f59e0b', icon: 'Hammer' },
  { name: 'Dla kotów i zwierząt', color: '#8b5cf6', icon: 'Cat' },
  { name: 'Rachunki i media', color: '#3b82f6', icon: 'Zap' },
  { name: 'Zdrowie i kosmetyki', color: '#ec4899', icon: 'HeartPulse' },
  { name: 'Transport i paliwo', color: '#06b6d4', icon: 'Car' },
  { name: 'Rozrywka i hobby', color: '#a855f7', icon: 'Gamepad2' },
  { name: 'Odzież i obuwie', color: '#f97316', icon: 'Shirt' },
  { name: 'Edukacja i książki', color: '#6366f1', icon: 'BookOpen' },
  { name: 'Inne wydatki', color: '#64748b', icon: 'MoreHorizontal' },
];

export const INITIAL_INCOME_CATEGORIES = [
  'Wypłata z etatu',
  'Premia / Bonus',
  'Freelance / Dodatkowe zlecenia',
  'Świadczenia / 800+',
  'Zwrot podatku / Inwestycje',
  'Inne dochody',
];

export const INITIAL_BUDGET_LIMITS: BudgetLimit[] = [
  { id: 'lim-1', category: 'Jedzenie i artykuły spożywcze', monthlyLimit: 2200, color: '#10b981', notifyAtPercent: 80 },
  { id: 'lim-2', category: 'Remont i dom', monthlyLimit: 1200, color: '#f59e0b', notifyAtPercent: 80 },
  { id: 'lim-3', category: 'Dla kotów i zwierząt', monthlyLimit: 450, color: '#8b5cf6', notifyAtPercent: 85 },
  { id: 'lim-4', category: 'Rachunki i media', monthlyLimit: 1600, color: '#3b82f6', notifyAtPercent: 90 },
  { id: 'lim-5', category: 'Transport i paliwo', monthlyLimit: 600, color: '#06b6d4', notifyAtPercent: 80 },
  { id: 'lim-6', category: 'Rozrywka i hobby', monthlyLimit: 400, color: '#a855f7', notifyAtPercent: 75 },
  { id: 'lim-7', category: 'Zdrowie i kosmetyki', monthlyLimit: 350, color: '#ec4899', notifyAtPercent: 80 },
];

export const INITIAL_SHOPPING_LISTS: ShoppingList[] = [
  {
    id: 'list-1',
    name: 'Obiad & Kolacja na weekend',
    category: 'Jedzenie i obiad',
    icon: 'Utensils',
    color: '#10b981',
    description: 'Składniki na pieczonego łososia i zupę krem dyniową',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'list-2',
    name: 'Remont przedpokoju i sypialni',
    category: 'Remont mieszkania',
    icon: 'Hammer',
    color: '#f59e0b',
    description: 'Materiały i narzędzia malarskie z Castoramy',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'list-3',
    name: 'Dla kotów (Mruczek & Lunka)',
    category: 'Dla kotów',
    icon: 'Cat',
    color: '#8b5cf6',
    description: 'Zapas karmy mokrej, żwirku i witamin',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'list-4',
    name: 'Chemia domowa & Środki czystości',
    category: 'Dom',
    icon: 'Sparkles',
    color: '#06b6d4',
    description: 'Uzupełnienie zapasów do pralki i zmywarki',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_SHOPPING_ITEMS: ShoppingItem[] = [
  // Obiad
  {
    id: 'item-1',
    listId: 'list-1',
    name: 'Filet ze świeżego łososia (500g)',
    estimatedPrice: 42.0,
    quantity: 1,
    unit: 'szt.',
    isCompleted: false,
    category: 'Jedzenie i artykuły spożywcze',
    notes: 'Najlepiej dziki łosoś pacyficzny',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-2',
    listId: 'list-1',
    name: 'Dynia piżmowa lub Hokkaido',
    estimatedPrice: 12.5,
    quantity: 1,
    unit: 'szt.',
    isCompleted: true,
    category: 'Jedzenie i artykuły spożywcze',
    notes: 'Do zupy krem',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-3',
    listId: 'list-1',
    name: 'Mleczko kokosowe bio',
    estimatedPrice: 7.99,
    quantity: 2,
    unit: 'puszka',
    isCompleted: false,
    category: 'Jedzenie i artykuły spożywcze',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-4',
    listId: 'list-1',
    name: 'Świeży rozmaryn i czosnek',
    estimatedPrice: 6.0,
    quantity: 1,
    unit: 'opak.',
    isCompleted: false,
    category: 'Jedzenie i artykuły spożywcze',
    createdAt: new Date().toISOString(),
  },

  // Remont
  {
    id: 'item-5',
    listId: 'list-2',
    name: 'Farba lateksowa do ścian (Biała satyna 5L)',
    estimatedPrice: 129.0,
    quantity: 1,
    unit: 'wiadro',
    isCompleted: false,
    category: 'Remont i dom',
    notes: 'Magnat Ceramic lub Dulux',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-6',
    listId: 'list-2',
    name: 'Zestaw wałków malarskich z kuwetą',
    estimatedPrice: 38.5,
    quantity: 1,
    unit: 'kpl.',
    isCompleted: true,
    category: 'Remont i dom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-7',
    listId: 'list-2',
    name: 'Taśma malarska papierowa precyzyjna (2 rolki)',
    estimatedPrice: 24.0,
    quantity: 2,
    unit: 'szt.',
    isCompleted: false,
    category: 'Remont i dom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-8',
    listId: 'list-2',
    name: 'Folia ochronna gruba malarska',
    estimatedPrice: 15.0,
    quantity: 3,
    unit: 'szt.',
    isCompleted: false,
    category: 'Remont i dom',
    createdAt: new Date().toISOString(),
  },

  // Dla kotów
  {
    id: 'item-9',
    listId: 'list-3',
    name: 'Karma mokra Feringa / MACs (zestaw 6x400g)',
    estimatedPrice: 74.9,
    quantity: 2,
    unit: 'opak.',
    isCompleted: false,
    category: 'Dla kotów i zwierząt',
    notes: 'Smak indyk + krewetki dla Mruczka',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-10',
    listId: 'list-3',
    name: 'Żwirek zbrylający bezzapachowy (10L)',
    estimatedPrice: 39.0,
    quantity: 1,
    unit: 'worek',
    isCompleted: false,
    category: 'Dla kotów i zwierząt',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-11',
    listId: 'list-3',
    name: 'Przysmaki dentystyczne dla kotów',
    estimatedPrice: 12.0,
    quantity: 2,
    unit: 'opak.',
    isCompleted: true,
    category: 'Dla kotów i zwierząt',
    createdAt: new Date().toISOString(),
  },

  // Chemia
  {
    id: 'item-12',
    listId: 'list-4',
    name: 'Kapsułki do zmywarki Fairy Platinum (70 szt)',
    estimatedPrice: 58.0,
    quantity: 1,
    unit: 'opak.',
    isCompleted: false,
    category: 'Remont i dom',
    createdAt: new Date().toISOString(),
  },
];

// Generate dates relative to today
const today = new Date();
const formatDate = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_BILLS: Bill[] = [
  {
    id: 'bill-1',
    name: 'Rachunek za prąd (Tauron)',
    serviceType: 'prąd',
    provider: 'Tauron Dystrybucja S.A.',
    amount: 245.8,
    dueDate: formatDate(2), // Due in 2 days -> upcoming alert!
    billingCycle: 'miesięcznie',
    pricingType: 'variable', // Opłata zmienna (wg licznika)
    status: 'pending',
    meterReading: {
      previous: 1420,
      current: 1565,
      unit: 'kWh',
      readingDate: formatDate(-10),
    },
    notes: 'Płatność przez aplikację bankową / e-BOK',
    paymentHistory: [
      {
        id: 'hist-1',
        amount: 238.4,
        paidDate: formatDate(-32),
        billingPeriod: 'Lipiec 2026',
        notes: 'Opłacono na czas',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bill-2',
    name: 'Gaz ziemny - ogrzewanie i kuchenka',
    serviceType: 'gaz',
    provider: 'PGNiG Obrót Detaliczny',
    amount: 118.4,
    dueDate: formatDate(6),
    billingCycle: 'co 2 miesiące',
    pricingType: 'variable', // Opłata zmienna
    status: 'pending',
    meterReading: {
      previous: 820.4,
      current: 845.2,
      unit: 'm³',
      readingDate: formatDate(-5),
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bill-3',
    name: 'Czynsz administracyjny & fundusz remontowy',
    serviceType: 'czynsz',
    provider: 'Spółdzielnia Mieszkaniowa "Zielone Osiedle"',
    amount: 680.0,
    dueDate: formatDate(10),
    billingCycle: 'miesięcznie',
    pricingType: 'fixed', // Opłata stała
    status: 'pending',
    notes: 'Zawiera zaliczkę na CO i wywóz śmieci',
    paymentHistory: [
      {
        id: 'hist-3',
        amount: 680.0,
        paidDate: formatDate(-28),
        billingPeriod: 'Sierpień 2026',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bill-4',
    name: 'Woda zimna i ścieki (MPWiK)',
    serviceType: 'woda',
    provider: 'Miejskie Przedsiębiorstwo Wodociągów',
    amount: 142.5,
    dueDate: formatDate(-3),
    billingCycle: 'miesięcznie',
    pricingType: 'variable', // Opłata zmienna
    status: 'paid',
    paymentDate: formatDate(-3),
    lastPaidAmount: 142.5,
    meterReading: {
      previous: 124.5,
      current: 135.2,
      unit: 'm³',
    },
    notes: 'Opłacone kartą przez e-BOK',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bill-5',
    name: 'Światłowód 600 Mb/s + Pakiet TV',
    serviceType: 'internet',
    provider: 'Orange Polska',
    amount: 89.99,
    dueDate: formatDate(14),
    billingCycle: 'miesięcznie',
    pricingType: 'fixed', // Opłata stała
    status: 'pending',
    paymentHistory: [
      {
        id: 'hist-5',
        amount: 89.99,
        paidDate: formatDate(-25),
        billingPeriod: 'Sierpień 2026',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bill-6',
    name: 'Odpady komunalne (Wywóz śmieci)',
    serviceType: 'śmieci',
    provider: 'Urząd Miasta - Wydział Gospodarki Odpadami',
    amount: 85.0,
    dueDate: formatDate(15),
    billingCycle: 'miesięcznie',
    pricingType: 'fixed', // Opłata stała
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Incomes with rich comments
  {
    id: 'inc-1',
    type: 'income',
    amount: 7200.0,
    category: 'Wypłata z etatu',
    date: formatDate(-1),
    title: 'Wynagrodzenie za pracę (etat główny)',
    comment: 'Wypłata na konto za sierpień wraz z dodatkiem stażowym i rozliczeniem dyżuru',
    isRecurring: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inc-2',
    type: 'income',
    amount: 1850.0,
    category: 'Freelance / Dodatkowe zlecenia',
    date: formatDate(-4),
    title: 'Faktura za projekt strony WWW i audyt UX',
    comment: 'Zlecenie dodatkowe dla lokalnej kawiarni rzemieślniczej (klient: Dobra Kawa sp. z o.o.)',
    isRecurring: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inc-3',
    type: 'income',
    amount: 800.0,
    category: 'Świadczenia / 800+',
    date: formatDate(-10),
    title: 'Świadczenie wychowawcze 800+',
    comment: 'Przelew z ZUS na rachunek bieżący',
    isRecurring: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inc-4',
    type: 'income',
    amount: 1200.0,
    category: 'Premia / Bonus',
    date: formatDate(-20),
    title: 'Premia kwartalna za wyniki zespołu',
    comment: 'Uznaniowy bonus za terminowe zakończenie etapu Q3',
    isRecurring: false,
    createdAt: new Date().toISOString(),
  },

  // Expenses across categories
  {
    id: 'exp-1',
    type: 'expense',
    amount: 215.6,
    category: 'Jedzenie i artykuły spożywcze',
    date: formatDate(-1),
    title: 'Zakupy spożywcze na obiad i zapasy',
    comment: 'Sklep Biedronka: warzywa, mięso, nabiał, pieczywo rzemieślnicze',
    receiptStoreName: 'Biedronka',
    createdAt: new Date().toISOString(),
    receiptItems: [
      { name: 'Filet z indyka 600g', price: 21.9, category: 'Jedzenie i artykuły spożywcze' },
      { name: 'Oliwa z oliwek Extra Virgin', price: 34.5, category: 'Jedzenie i artykuły spożywcze' },
      { name: 'Ser Gouda w kawałku', price: 14.8, category: 'Jedzenie i artykuły spożywcze' },
      { name: 'Warzywa i owoce (pomidory, jabłka)', price: 28.4, category: 'Jedzenie i artykuły spożywcze' },
      { name: 'Drobne artykuły i pieczywo', price: 116.0, category: 'Jedzenie i artykuły spożywcze' },
    ],
  },
  {
    id: 'exp-2',
    type: 'expense',
    amount: 340.5,
    category: 'Remont i dom',
    date: formatDate(-3),
    title: 'Materiały do renowacji salonu',
    comment: 'Castorama: farba ceramiczna Magnat, grunt, taśmy malarskie i pędzle',
    receiptStoreName: 'Castorama',
    createdAt: new Date().toISOString(),
    receiptItems: [
      { name: 'Farba Magnat Ceramic 5L', price: 169.0, category: 'Remont i dom' },
      { name: 'Grunt głęboko penetrujący 5L', price: 42.5, category: 'Remont i dom' },
      { name: 'Zestaw wałków i kuweta malarska', price: 55.0, category: 'Remont i dom' },
      { name: 'Folie malarskie i taśmy', price: 74.0, category: 'Remont i dom' },
    ],
  },
  {
    id: 'exp-3',
    type: 'expense',
    amount: 198.0,
    category: 'Dla kotów i zwierząt',
    date: formatDate(-5),
    title: 'Karma mokra i żwirek dla kotów',
    comment: 'Maxi Zoo: zapas bezzbożowej karmy Animonda Carny dla kotów oraz duży żwirek bentonitowy',
    receiptStoreName: 'Maxi Zoo',
    createdAt: new Date().toISOString(),
    receiptItems: [
      { name: 'Pakiet puszek Animonda Carny 12x400g', price: 119.0, category: 'Dla kotów i zwierząt' },
      { name: 'Żwirek Super Benek Lawenda 20L', price: 54.0, category: 'Dla kotów i zwierząt' },
      { name: 'Przysmak kabanosy z łososiem', price: 25.0, category: 'Dla kotów i zwierząt' },
    ],
  },
  {
    id: 'exp-4',
    type: 'expense',
    amount: 142.5,
    category: 'Rachunki i media',
    date: formatDate(-3),
    title: 'Opłata za wodę i ścieki',
    comment: 'Rozliczenie faktury MPWiK za ubiegły miesiąc',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-5',
    type: 'expense',
    amount: 280.0,
    category: 'Transport i paliwo',
    date: formatDate(-7),
    title: 'Tankowanie paliwa Pb95',
    comment: 'Stacja Orlen - pełny bak przed wyjazdem rodzinnym',
    receiptStoreName: 'Orlen',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-6',
    type: 'expense',
    amount: 120.0,
    category: 'Zdrowie i kosmetyki',
    date: formatDate(-9),
    title: 'Apteka - witaminy i leki sezonowe',
    comment: 'Witamina D3, magnez, krople do oczu',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-7',
    type: 'expense',
    amount: 165.0,
    category: 'Rozrywka i hobby',
    date: formatDate(-12),
    title: 'Bilety do teatru i kawa',
    comment: 'Wyjście weekendowe do Teatru Miejskiego na spektakl',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-8',
    type: 'expense',
    amount: 185.0,
    category: 'Jedzenie i artykuły spożywcze',
    date: formatDate(-15),
    title: 'Zakupy Lidl - produkty tygodnia',
    comment: 'Nabiał bio, orzechy, ryby i owoce',
    receiptStoreName: 'Lidl',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-9',
    type: 'expense',
    amount: 85.0,
    category: 'Dla kotów i zwierząt',
    date: formatDate(-18),
    title: 'Wizyta kontrolna u weterynarza',
    comment: 'Okresowe odrobaczenie i obcięcie pazurków dla Lunki',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-10',
    type: 'expense',
    amount: 450.0,
    category: 'Remont i dom',
    date: formatDate(-22),
    title: 'Nowa bateria kuchenna i syfon',
    comment: 'Wymiana cieknącej baterii w zlewie kuchennym (Leroy Merlin)',
    createdAt: new Date().toISOString(),
  },
];

export const SAMPLE_RECEIPTS = [
  {
    id: 'rec-1',
    title: 'Biedronka - Zakupy spożywcze & dla kota',
    storeName: 'BIEDRONKA Jeronimo Martins Polska S.A.',
    date: formatDate(0),
    totalAmount: 148.75,
    currency: 'PLN',
    dominantCategory: 'Jedzenie i artykuły spożywcze',
    summary: 'Paragon z Biedronki zawierający produkty na obiad weekendowy oraz karmę dla kota.',
    items: [
      { name: 'PIERŚ Z KURCZAKA 1KG', price: 23.99, quantity: 1, category: 'Jedzenie i artykuły spożywcze', notes: 'Na obiad' },
      { name: 'ZIEMNIAKI WCZESNE 2.5KG', price: 7.49, quantity: 1, category: 'Jedzenie i artykuły spożywcze', notes: 'Warzywa' },
      { name: 'ŚMIETANA 18% POLMLEK 330G', price: 4.89, quantity: 2, category: 'Jedzenie i artykuły spożywcze' },
      { name: 'POMIDORY MALINOWE 1KG', price: 9.99, quantity: 1, category: 'Jedzenie i artykuły spożywcze' },
      { name: 'KAWA ZIARNISTA LAVAZZA 1KG', price: 59.99, quantity: 1, category: 'Jedzenie i artykuły spożywcze' },
      { name: 'KARMA DLA KOTA SHEBA 4X85G', price: 14.50, quantity: 1, category: 'Dla kotów i zwierząt', notes: 'Dla kotka' },
      { name: 'CHLEB ŻYTNI NA ZAKWASIE', price: 5.90, quantity: 1, category: 'Jedzenie i artykuły spożywcze' },
      { name: 'PŁYN DO NACZYŃ PUR 750ML', price: 9.99, quantity: 1, category: 'Remont i dom', notes: 'Chemia' },
    ],
  },
  {
    id: 'rec-2',
    title: 'Castorama - Remont i malowanie pokoju',
    storeName: 'CASTORAMA POLSKA Sp. z o.o.',
    date: formatDate(-1),
    totalAmount: 382.40,
    currency: 'PLN',
    dominantCategory: 'Remont i dom',
    summary: 'Zakupy narzędzi i farby do remontu mieszkania.',
    items: [
      { name: 'FARBA BECKERS ELEGANT BIAŁA 5L', price: 149.00, quantity: 1, category: 'Remont i dom', notes: 'Ściany' },
      { name: 'GRUNT AKRYLOWY PRIMACOL 5L', price: 34.90, quantity: 1, category: 'Remont i dom' },
      { name: 'ZESTAW WAŁKÓW ANZA MICROFIBRA', price: 49.90, quantity: 1, category: 'Remont i dom' },
      { name: 'TAŚMA MALARSKA TESA GOLD 50MM', price: 28.80, quantity: 2, category: 'Remont i dom' },
      { name: 'GIPS SZPACHLOWY DOLINA NIDY 5KG', price: 22.00, quantity: 1, category: 'Remont i dom' },
      { name: 'FOLIA MALARSKA GRUBA 4X5M', price: 18.00, quantity: 2, category: 'Remont i dom' },
      { name: 'PAPIER ŚCIERNY GRADACJA 180 (5szt)', price: 15.00, quantity: 1, category: 'Remont i dom' },
      { name: 'KLEJ MONTAŻOWY MAMUT', price: 36.00, quantity: 1, category: 'Remont i dom' },
    ],
  },
  {
    id: 'rec-3',
    title: 'Maxi Zoo - Zapas dla kotów',
    storeName: 'MAXI ZOO POLSKA',
    date: formatDate(-2),
    totalAmount: 214.50,
    currency: 'PLN',
    dominantCategory: 'Dla kotów i zwierząt',
    summary: 'Zakup karmy premium, żwirku i drapaka dla kotów.',
    items: [
      { name: 'REAL NATURE PUSZKA DLA KOTA 6X400G', price: 84.90, quantity: 1, category: 'Dla kotów i zwierząt', notes: 'Wołowina i drób' },
      { name: 'ŻWIREK PREMIERE SENSITIVE 12KG', price: 69.90, quantity: 1, category: 'Dla kotów i zwierząt', notes: 'Drobny bentonit' },
      { name: 'PASTA ODKŁACZAJĄCA GIMCAT 100G', price: 24.80, quantity: 1, category: 'Dla kotów i zwierząt' },
      { name: 'MYSZKI Z KOCIMIĘTKĄ (ZESTAW 3 SZT)', price: 14.90, quantity: 1, category: 'Dla kotów i zwierząt' },
      { name: 'PRZYSMAKI COSMA SNACKIES LIOFILIZOWANE', price: 20.00, quantity: 1, category: 'Dla kotów i zwierząt' },
    ],
  },
];
